import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { getConfig } from './config/env.js';
import { auditToolSurface } from './security/read-only-policy.js';
import { AppError } from './utils/errors.js';
import { createLogger } from './utils/logger.js';
import { clearRegisteredToolMeta, getRegisteredToolMeta } from './mcp/tool-registry.js';
import { registerAdoProjectTools } from './mcp/tools/ado/project.tools.js';
import { registerAdoWorkItemTools } from './mcp/tools/ado/work-item.tools.js';
import { registerQueryTools } from './mcp/tools/ado/query.tools.js';
import { registerAdoWriteTools } from './mcp/tools/ado/write.tools.js';
import { registerAnalysisTools } from './mcp/tools/analysis/analysis.tools.js';
import { registerGovernanceTools } from './mcp/tools/analysis/governance.tools.js';
import { registerTeamLeadTools } from './mcp/tools/teamlead/teamlead.tools.js';
import { registerHealthTools } from './mcp/tools/system/health.tools.js';
import { registerSkillTools } from './mcp/tools/skills/skill.tools.js';
import { registerCustomSkillTools } from './mcp/tools/skills/custom-skill.tools.js';
import { registerResources } from './mcp/resources/index.js';
import { registerSkillResources } from './mcp/resources/skills.js';
import { registerPrompts } from './mcp/prompts/index.js';
import { getDatabase } from './database/connection.js';
import { getSkills, validateSkills } from './skills/registry.js';
import { InternalSkillRegistry } from './core/skill-registry.js';

const log = createLogger('server');

export const SERVER_NAME = 'sherlock';
export const SERVER_VERSION = '1.0.0';

const INSTRUCTIONS = `S.H.E.R.L.O.C.K. - Sprint Health, Execution, Risk, Logistics, Operations & Coordination Knowledge.

SCOPE
All Azure DevOps tools operate on the configured organization, project and team (ADO_ORGANIZATION / ADO_PROJECT / ADO_TEAM). You never need to pass organization, project or team unless a tool explicitly supports an override.

AZURE DEVOPS WORK ITEMS ARE READ-ONLY
This server cannot create, update, delete or assign work items, change state, priority, area or iteration, add comments, or modify backlogs, sprints, repositories or pipelines. When asked for a work-item change, say plainly that work items are read-only and offer an analysis or recommendation.

SAVED QUERIES
The one Azure DevOps mutation that exists is \`create_ado_query\`, limited to controlled saved-query creation/reuse. Saved queries default to \`My Queries/{ADO_TEAM}\` and are isolated by configured team. Do not use Shared Queries unless explicitly asked. If the folder cannot be used, report QUERY_FOLDER_NOT_FOUND and do not invent a URL.

REAL DATA VS ANALYSIS
Tools prefixed \`ado_\` return measured Azure DevOps data. Tools prefixed \`analysis_\`, \`tl_analyze_\` and the review generators return an envelope with a \`facts\` block (measured) plus \`observations\`, \`concerns\` and \`recommendations\` (generated by this server's heuristics, with the thresholds stated in \`methodology\`). Keep the two apart when you answer, and never invent a work item, person, date or metric that is not in the tool output. If a value could not be measured, the tool says so - pass that on rather than estimating.

SKILLS COME FIRST FOR RECURRING WORKFLOWS
When asked for a briefing, workload, sprint, backlog, deadline or composed review, call \`skill_execute\` with the skill name (built-in or custom). Do not chain many \`ado_*\` tools for those workflows. Use custom skill tools to show, compose, create and manage reusable analysis skills.

WHERE TO START
- "How is my team doing?" -> \`skill_execute\` \`daily-standup-starter\` or \`team-morning-brief\`
- "How is the project?" -> \`skill_execute\` \`project-health-analysis\`
- "Who is overloaded?" -> \`skill_execute\` \`workload-analysis\`
- "What is at risk?" -> \`skill_execute\` \`deadline-risk-analysis\`
- "Who should take #1234?" -> \`skill_execute\` \`work-assignment-recommendation\`
- Combine skills -> \`sherlock_compose_skill\` (confirm=false, then true)
- One-off lookups -> \`ado_*\` tools
- Prompts (daily_team_review, sprint_review, tl_weekly_review) still orchestrate workflows.`;

export interface BuildServerOptions {
    /** Skip opening the SQLite audit database. Used by tests that stub the repositories. */
    skipDatabaseInit?: boolean;
}

/**
 * Builds the MCP server: registers every tool, resource and prompt, then audits the
 * resulting tool surface against the read-only policy before returning.
 */
export function buildServer(options: BuildServerOptions = {}): McpServer {
    const config = getConfig();

    if (!options.skipDatabaseInit) {
        // Open (and migrate) the audit database eagerly so a misconfigured
        // DATABASE_URL fails at startup rather than mid-conversation.
        getDatabase();
        InternalSkillRegistry.loadFromDatabase();
    }

    const server = new McpServer(
        { name: SERVER_NAME, version: SERVER_VERSION },
        {
            instructions: INSTRUCTIONS,
            capabilities: { tools: {}, resources: {}, prompts: {}, logging: {} }
        }
    );

    clearRegisteredToolMeta();

    registerAdoProjectTools(server);
    registerAdoWorkItemTools(server);
    registerQueryTools(server);
    registerAdoWriteTools(server);
    registerAnalysisTools(server);
    registerGovernanceTools(server);
    registerTeamLeadTools(server);
    registerHealthTools(server);
    registerSkillTools(server);
    registerCustomSkillTools(server);
    registerResources(server);
    registerSkillResources(server);
    registerPrompts(server);

    assertReadOnlyToolSurface();
    assertSkillCatalogueIsValid();

    const tools = getRegisteredToolMeta();
    log.info('MCP server ready', {
        name: SERVER_NAME,
        version: SERVER_VERSION,
        tools: tools.length,
        readOnlyTools: tools.filter(tool => tool.readOnly).length,
        skills: getSkills().length,
        organization: config.ado.organization,
        project: config.ado.project,
        team: config.ado.team,
        adoConfigured: config.ado.configured
    });

    return server;
}

/**
 * Startup guarantee: no registered tool may look like an Azure DevOps mutation or
 * accept HTTP-level parameters. A violation aborts startup.
 */
export function assertReadOnlyToolSurface(): void {
    const tools = getRegisteredToolMeta();
    const violations = auditToolSurface(tools);
    if (violations.length > 0) {
        throw new AppError(
            'READ_ONLY_VIOLATION',
            `Read-only tool surface audit failed:\n${violations.map(violation => `  - ${violation.tool}: ${violation.reason}`).join('\n')}`
        );
    }

    // Permitted non-read-only tool: controlled saved query creation.
    const mutating = tools.filter(tool => !tool.readOnly).map(tool => tool.name);
    const allowedMutating = ['create_ado_query'];
    const invalidMutating = mutating.filter(name => !allowedMutating.includes(name));
    
    if (invalidMutating.length > 0) {
        throw new AppError(
            'READ_ONLY_VIOLATION',
            `Only ${allowedMutating.join(' and ')} may be non-read-only, but found: ${invalidMutating.join(', ')}.`
        );
    }
}

/**
 * Startup guarantee for the skill catalogue: every skill is fully specified and
 * references only tools this server actually exposes. A skill that names a
 * missing tool would instruct the model to call something imaginary, so it
 * aborts startup rather than reaching a client.
 */
export function assertSkillCatalogueIsValid(): void {
    const issues = validateSkills(
        getSkills(),
        getRegisteredToolMeta().map(tool => tool.name)
    );
    if (issues.length > 0) {
        throw new AppError(
            'INVALID_INPUT',
            `Skill catalogue validation failed:\n${issues.map(issue => `  - ${issue.skill}: ${issue.reason}`).join('\n')}`
        );
    }
}
